import {handle} from './worker.mjs';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const data=JSON.parse(await readFile(new URL('../Career%20Assessments%20Web/search-index.json',import.meta.url),'utf8'));
const fetcher=async()=>Response.json(data);
const get=async(path,method='GET')=>handle(new Request('https://api.careerfactorynd.org'+path,{method}),fetcher);
let r=await get('/v1/careers');assert.equal(r.status,200);let d=await r.json();assert.equal(d.total,193);assert.equal(d.careers.length,20);
d=await(await get('/v1/careers?area=jobs-you-can-start-now&limit=100')).json();assert.equal(d.total,22);
d=await(await get('/v1/careers?q=private%20investigator')).json();assert.equal(d.total,1);assert.match(d.careers[0].assessmentUrl,/^https:\/\/careerfactorynd.org\//);
d=await(await get('/v1/careers/skilled-trades/electrician')).json();assert.equal(d.career.name,'Electrician');
assert.equal((await(await get('/v1/areas')).json()).total,12);
assert.equal((await get('/v1/careers?limit=-1')).status,400);
assert.equal((await get('/v1/careers?offset=oops')).status,400);
assert.equal((await get('/v1/careers?area=missing')).status,400);
assert.equal((await get('/v1/careers/missing/nope')).status,404);
assert.equal((await get('/v1/careers','POST')).status,405);
assert.equal((await get('/v1/careers','OPTIONS')).headers.get('Access-Control-Allow-Origin'),'*');
assert.equal(await(await get('/v1/careers','HEAD')).text(),'');
assert.equal((await handle(new Request('https://api.careerfactorynd.org/v1/careers'),async()=>{throw new Error('offline')})).status,503);
console.log('PASS: API counts, search, area filter, details, pagination validation, CORS, read-only methods, HEAD and upstream failure.');
